import Head from 'next/head';
import React from 'react';
import Switch from '../components/Switch/Switch';

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
            </Head>
            <main className='flex h-screen w-screen items-center justify-center'>
                <Switch />
            </main>
        </>
    );
}
